### PR TITLE
fix IncludeSubdirectories check

### LINKED ISSUE #15: RegisterAdditionalFileWatchersForSymLinkDirs throws error
I just received this error log from a user of my application which utilizes FileWatcherEx:

```
System.UnauthorizedAccessException: Access to the path 'c:\program files (x86)\steam\steamapps\common\wallpaper_engine\ui\uicache\welcome\user\WidevineCdm\4.10.2391.0' is denied.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String, Boolean )
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String, FindTransform, EnumerationOptions, Boolean)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String, String, EnumerationOptions, Boolean)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String, String, SearchTarget, EnumerationOptions)
   at System.IO.DirectoryInfo.GetDirectories(String, EnumerationOptions)
   at FileWatcherEx.Helpers.SymlinkAwareFileWatcher.RegisterAdditionalFileWatchersForSymLinkDirs(String path)
   at FileWatcherEx.Helpers.SymlinkAwareFileWatcher.RegisterAdditionalFileWatchersForSymLinkDirs(String path)
   at FileWatcherEx.Helpers.SymlinkAwareFileWatcher.RegisterAdditionalFileWatchersForSymLinkDirs(String path)
   at FileWatcherEx.Helpers.SymlinkAwareFileWatcher.RegisterAdditionalFileWatchersForSymLinkDirs(String path)
   at FileWatcherEx.Helpers.SymlinkAwareFileWatcher.RegisterAdditionalFileWatchersForSymLinkDirs(String path)
   at FileWatcherEx.Helpers.SymlinkAwareFileWatcher.RegisterAdditionalFileWatchersForSymLinkDirs(String path)
   at FileWatcherEx.Helpers.SymlinkAwareFileWatcher.RegisterAdditionalFileWatchersForSymLinkDirs(String path)
   at FileWatcherEx.Helpers.SymlinkAwareFileWatcher.RegisterAdditionalFileWatchersForSymLinkDirs(String path)
   at FileWatcherEx.Helpers.SymlinkAwareFileWatcher.RegisterAdditionalFileWatchersForSymLinkDirs(String path)
   at FileWatcherEx.Helpers.SymlinkAwareFileWatcher.RegisterAdditionalFileWatchersForSymLinkDirs(String path)
   at SFP.Models.Steam.StartMonitorSteam() in C:\Users\Phantom\Documents\GitHub\SFP\SFP\Models\Steam.cs:line 188
```

[SFP.Models.Steam.StartMonitorSteam() can be found here](https://github.com/PhantomGamers/SFP/blob/6f0800e38f5b3ca02e685ab1923d59a1f4272432/SFP/Models/Steam.cs#L174-L187)

My application creates a new FileSystemWatcherEx instance with the given path in this case being `c:\program files (x86)\steam`, I do not have IncludeSubdirectories set to true for this instance so why does `RegisterAdditionalFileWatchersForSymLinkDirs` run on all sub-directories of this folder?

I'm not sure if this is a bug or if there is some reason for this functionality, but if it is intended to go through all subdirectories like this then I think there needs to be a try catch implemented because there can be cases where the user has permissions for the base folder but not to certain subdirectories in that base folder.

### PR DESCRIPTION
**Pull request by PhantomGamers**
IncludeSubdirectories was being checked after searching for all subdirectories, for each subdirectory found.

Let's check before checking for subdirectories instead

Partially fixes #15 but does not fix cases where monitoring subdirectories might fail in cases where there are cyclical symlinks

### CODE REVIEW

**Review by d2phap — APPROVED** [review]
Thanks for the fix! I will publish new version.

File: Source/FileWatcherEx/Helpers/SymlinkAwareFileWatcher.cs [hunk 1]
```diff
@@ -178,7 +180,7 @@ internal void TryRegisterFileWatcherForSymbolicLinkDir(string path)
     {
         try
         {
-            if (IsSymbolicLinkDirectory(path) && IncludeSubdirectories && !FileWatchers.ContainsKey(path))
+            if (IsSymbolicLinkDirectory(path) && !FileWatchers.ContainsKey(path))
```
Comment (d2phap) [inline Source/FileWatcherEx/Helpers/SymlinkAwareFileWatcher.cs:183]: @PhantomGamers removing this condition cause the test failed

image

Comment (PhantomGamers) [reply Source/FileWatcherEx/Helpers/SymlinkAwareFileWatcher.cs:183]: My bad I didn't actually check the tests, just checked to see if the code fixed the issue I was having. I'll look into it right now
